import {
  SiAngular,
  SiCsharp,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElectron,
  SiExpress,
  SiGo,
  SiJava,
  SiJavascript,
  SiLaravel,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiReact,
  SiRust,
  SiSpring,
  SiSpringboot,
  SiTypescript,
} from "react-icons/si";

export const tagMap = new Map<string, JSX.Element>([
  ["nextjs", <SiNextdotjs />],
  ["django", <SiDjango />],
  ["express", <SiExpress />],
  ["nodejs", <SiNodedotjs />],
  ["spring", <SiSpring />],
  ["springboot", <SiSpringboot />],
  ["dotnet", <SiDotnet />],
  ["laravel", <SiLaravel />],
  ["react", <SiReact />],
  ["electron", <SiElectron />],
  ["angular", <SiAngular />],
  ["docker", <SiDocker />],
  ["postgresql", <SiPostgresql />],
  ["javascript", <SiJavascript />],
  ["typescript", <SiTypescript />],
  ["java", <SiJava />],
  ["csharp", <SiCsharp />],
  ["rust", <SiRust />],
  ["php", <SiPhp />],
  ["golang", <SiGo />],
]);
