import {
  SiAngular,
  SiCsharp,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElectron,
  SiExpress,
  SiGo,
  SiJava,
  SiJavascript,
  SiLaravel,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiReact,
  SiRust,
  SiSpring,
  SiSpringboot,
  SiSupabase,
  SiTypescript,
} from "react-icons/si";

export const tagMap = new Map<string, JSX.Element>([
  ["nextjs", <SiNextdotjs title="NextJS" />],
  ["django", <SiDjango title="Django" />],
  ["express", <SiExpress title="ExpressJS" />],
  ["nodejs", <SiNodedotjs title="NodeJS" />],
  ["spring", <SiSpring title="Spring" />],
  ["springboot", <SiSpringboot title="Spring Boot" />],
  ["dotnet", <SiDotnet title=".NET Core" />],
  ["laravel", <SiLaravel title="Laravel" />],
  ["react", <SiReact title="React" />],
  ["electron", <SiElectron title="ElectronJS" />],
  ["angular", <SiAngular title="Angular" />],
  ["docker", <SiDocker title="Docker" />],
  ["supabase", <SiSupabase title="Supabase" />],
  ["postgresql", <SiPostgresql title="PostgreSQL" />],
  ["javascript", <SiJavascript title="JavaScript" />],
  ["typescript", <SiTypescript title="TypeScript" />],
  ["java", <SiJava title="Java" />],
  ["csharp", <SiCsharp title="C#" />],
  ["rust", <SiRust title="Rust" />],
  ["php", <SiPhp title="PHP" />],
  ["golang", <SiGo title="Golang" />],
]);
